'use strict'

const samochody = [
  {
    "tittle": "Kia K5 2025",
    "marka": "Kia",
    "model": "K5",
    "img": "images/cars/kia-k5-2025-02.webp",
    "rokProdukcji": 2025,
    "kolor": "srebrny",
    "przebiegKm": 15000,
    "opis": "Tutaj będzie opis samochodu",
    "id": 0,
    "cena": 45000
  },
  {
    "tittle": "Toyota Corolla 2020",
    "marka": "Toyota",
    "model": "Corolla",
    "img": "images/cars/Toyota Corolla 2020.avif",
    "rokProdukcji": 2020,
    "kolor": "czarny",
    "przebiegKm": 20000,
    "opis": "Tutaj będzie opis samochodu",
    "id": 1,
    "cena": 35000
  },
  {
    "tittle": "Ford Mustang GT 2023",
    "marka": "Ford",
    "model": "Mustang GT",
    "img": "images/cars/Ford Mustang GT.avif",
    "rokProdukcji": 2023,
    "kolor": "czerwony",
    "przebiegKm": 10000,
    "opis": "Tutaj będzie opis samochodu",
    "id": 2,
    "cena": 60000
  },
  {
    "tittle": "Chevrolet Camaro ZL1 2024",
    "marka": "Chevrolet",
    "model": "Camaro ZL1",
    "img": "images/cars/Chevrolet Camaro ZL1.avif",
    "rokProdukcji": 2024,
    "kolor": "niebieski",
    "przebiegKm": 5000,
    "opis": "Tutaj będzie opis samochodu",
    "id": 3,
    "cena": 70000
  },
  {
    "tittle": "Honda Civic 2022",
    "marka": "Honda",
    "model": "Civic",
    "img": "images/cars/Honda Civic.avif",
    "rokProdukcji": 2022,
    "kolor": "biały",
    "przebiegKm": 30000,
    "opis": "Tutaj będzie opis samochodu",
    "id": 4,
    "cena": 30000
  },
  {
    "tittle": "BMW 5 Series 2021",
    "marka": "BMW",
    "model": "5 Series",
    "img": "images/cars/BMW 5 Series.avif",
    "rokProdukcji": 2021,
    "kolor": "szary",
    "przebiegKm": 25000,
    "opis": "Tutaj będzie opis samochodu",
    "id": 5,
  },
  {
    "tittle": "Audi A4 2023",
    "marka": "Audi",
    "model": "A4",
    "img": "images/cars/Audi A4.jpg",
    "rokProdukcji": 2023,
    "kolor": "zielony",
    "przebiegKm": 15000,
    "opis": "Tutaj będzie opis samochodu",
    "id": 6,
  },
  {
    "tittle": "Mercedes-Benz",
    "marka": "Mercedes-Benz",
    "model": "E-Class",
    "img": "images/cars/Mercedez-Benz.avif",
    "rokProdukcji": 2022,
    "kolor": "czarny",
    "przebiegKm": 20000,
    "opis": "Tutaj będzie opis samochodu",
    "id": 7,
  },
  {
    "tittle": "Volkswagen Golf GTI 2023",
    "marka": "Volkswagen",
    "model": "Golf GTI",
    "img": "images/cars/Volkswagen Golf GTI.avif",
    "rokProdukcji": 2023,
    "kolor": "czerwony",
    "przebiegKm": 12000,
    "opis": "Tutaj będzie opis samochodu",
    "id": 8,
  },
  {
    "tittle": "Subaru WRX STI 2024",
    "marka": "Subaru",
    "model": "WRX STI",
    "img": "images/cars/Subaru WRX STI.jpg",
    "rokProdukcji": 2024,
    "kolor": "niebieski",
    "przebiegKm": 8000,
    "opis": "Tutaj będzie opis samochodu",
    "id": 9,
  },
  {
    "tittle": "Tesla Model S Plaid 2023",
    "marka": "Tesla",
    "model": "Model S Plaid",
    "img": "images/cars/Tesla Model S Plaid.jpg",
    "rokProdukcji": 2023,
    "kolor": "biały",
    "przebiegKm": 5000,
    "opis": "Tutaj będzie opis samochodu",
    "id": 10,
  },
  {
    "tittle": "Nissan GT-R Nismo 2024",
    "marka": "Nissan",
    "model": "GT-R Nismo",
    "img": "images/cars/Nissan GT-R Nismo.jpeg",
    "rokProdukcji": 2024,
    "kolor": "czarny",
    "przebiegKm": 15000,
    "opis": "Tutaj będzie opis samochodu",
    "id": 11,
  }
]
