const arrCars = [
  {
    id: 0,
    name: 'Kia K5 2025',
    brand: 'Kia',
    model: 'K5',
    img: 'images/cars/kia-k5-2025-02.webp',
    yearOfProduction: 2025,
    color: 'srebrny',
    mileage: 15000,
    description: 'Tutaj będzie opis samochodu',
    price: 45000,
  },
  {
    id: 1,
    name: 'Toyota Corolla 2020',
    brand: 'Toyota',
    model: 'Corolla',
    img: 'images/cars/Toyota Corolla 2020.avif',
    yearOfProduction: 2020,
    color: 'czarny',
    mileage: 20000,
    description: 'Tutaj będzie opis samochodu',
    price: 35000,
  },
  {
    id: 2,
    name: 'Ford Mustang GT ',
    brand: 'Ford',
    model: 'Mustang GT',
    img: 'images/cars/Ford Mustang GT.avif',
    yearOfProduction: 2023,
    color: 'czerwony',
    mileage: 10000,
    description: 'Tutaj będzie opis samochodu',
    price: 60000,
  },
  {
    id: 3,
    name: 'Chevrolet Camaro',
    brand: 'Chevrolet',
    model: 'Camaro ZL1',
    img: 'images/cars/Chevrolet Camaro ZL1.avif',
    yearOfProduction: 2024,
    color: 'niebieski',
    mileage: 5000,
    description: 'Tutaj będzie opis samochodu',
    price: 70000,
  },
  {
    id: 4,
    name: 'Honda Civic 2022',
    brand: 'Honda',
    model: 'Civic',
    img: 'images/cars/Honda Civic.avif',
    yearOfProduction: 2022,
    color: 'biały',
    mileage: 30000,
    description: 'Tutaj będzie opis samochodu',
    price: 30000,
  },
  {
    id: 5,
    name: 'BMW 5 Series 2021',
    brand: 'BMW',
    model: '5 Series',
    img: 'images/cars/BMW 5 Series.avif',
    yearOfProduction: 2021,
    color: 'szary',
    mileage: 25000,
    description: 'Tutaj będzie opis samochodu',
    price: 12000,
  },
  {
    id: 6,
    name: 'Audi A4 2023',
    brand: 'Audi',
    model: 'A4',
    img: 'images/cars/Audi A4.jpg',
    yearOfProduction: 2023,
    color: 'zielony',
    mileage: 15000,
    description: 'Tutaj będzie opis samochodu',
    price: 51000,
  },
  {
    id: 7,
    name: 'Mercedes-Benz',
    brand: 'Mercedes-Benz',
    model: 'E-Class',
    img: 'images/cars/Mercedez-Benz.avif',
    yearOfProduction: 2022,
    color: 'czarny',
    mileage: 20000,
    description: 'Tutaj będzie opis samochodu',
    price: 21000,
  },
  {
    id: 8,
    name: 'Volkswagen Golf GTI',
    brand: 'Volkswagen',
    model: 'Golf GTI',
    img: 'images/cars/Volkswagen Golf GTI.avif',
    yearOfProduction: 2023,
    color: 'czerwony',
    mileage: 12000,
    description: 'Tutaj będzie opis samochodu',
    price: 61000,
  },
  {
    id: 9,
    name: 'Subaru WRX STI 2024',
    brand: 'Subaru',
    model: 'WRX STI',
    img: 'images/cars/Subaru WRX STI.jpg',
    yearOfProduction: 2024,
    color: 'niebieski',
    mileage: 8000,
    description: 'Tutaj będzie opis samochodu',
    price: 41000,
  },
  {
    name: 'Tesla Model S Plaid 2023',
    brand: 'Tesla',
    model: 'Model S Plaid',
    img: 'images/cars/Tesla Model S Plaid.jpg',
    yearOfProduction: 2023,
    color: 'biały',
    mileage: 5000,
    description: 'Tutaj będzie opis samochodu',
    id: 10,
    price: 23000,
  },
  {
    name: 'Nissan GT-R Nismo 2024',
    brand: 'Nissan',
    model: 'GT-R Nismo',
    img: 'images/cars/Nissan GT-R Nismo.jpeg',
    yearOfProduction: 2024,
    color: 'czarny',
    mileage: 15000,
    description: 'Tutaj będzie opis samochodu',
    id: 11,
    price: 15000,
  },
];

const arrAccessories = [
  {
    id: 12,
    name: 'Kamera cofania',
    description:
      'Kamera cofania zapewnia dodatkową widoczność podczas cofania, co ułatwia parkowanie i manewrowanie pojazdem.',
    price: 250,
    img: 'images/accessories/kamera cofania.jpg',
  },
  {
    id: 13,
    name: 'Nawigacja GPS',
    description:
      'System nawigacji GPS pomaga w wyznaczaniu tras i wskazuje optymalne drogi, co ułatwia podróżowanie.',
    price: 400,
    img: 'images/accessories/nawigacja.jpeg',
  },
  {
    id: 14,
    name: 'System audio premium',
    description:
      'System audio premium oferuje wysoką jakość dźwięku, uprzyjemniając podróżowanie.',
    price: 600,
    img: 'images/accessories/audio.jpg',
  },
  {
    id: 15,
    name: 'Tapicerka skórzana',
    description:
      'Tapicerka skórzana dodaje elegancji wnętrzu samochodu oraz zapewnia wygodę podczas podróży.',
    price: 800,
    img: 'images/accessories/tapicerka.avif',
  },
  {
    id: 16,
    name: 'Ogrzewane fotele',
    description:
      'Ogrzewane fotele zapewniają komfort cieplny w chłodne dni, eliminując uczucie zimna podczas jazdy. Przydatne podczas wyjazdu w góry.',
    price: 350,
    img: 'images/accessories/podrzewaneFotele.jpg',
  },
  {
    id: 17,
    name: 'System monitorowania martwego pola',
    description:
      'System monitorowania martwego pola ostrzega kierowcę o obiektach znajdujących się poza jego polem widzenia.',
    price: 500,
    img: 'images/accessories/sysMonitMartwegoPola.jpg',
  },
  {
    id: 18,
    name: 'System rozpoznawania znaków drogowych',
    description:
      'Informuje kierowcę o obowiązujących ograniczeniach prędkości i innych znakach drogowych,',
    price: 450,
    img: 'images/accessories/znakiDrogowe.webp',
  },
  {
    id: 19,
    name: 'Dach panoramiczny',
    description:
      'Dach panoramiczny zapewnia widok na niebo i otoczenie, tworząc przestronne i jasne wnętrze samochodu.',
    price: 1200,
    img: 'images/accessories/dachPanoramiczny.jpg',
  },
  {
    id: 20,
    name: 'System automatycznego parkowania',
    description:
      'System automatycznego parkowania umożliwia precyzyjne parkowanie samochodu, co ułatwia manewrowanie w ciasnych miejscach.',
    price: 700,
    img: 'images/accessories/autoParkowanie.jpg',
  },
  {
    id: 21,
    name: 'Wspomaganie pasa ruchu',
    description:
      'Wspomaganie pasa ruchu pomaga kierowcy utrzymać pojazd na właściwym pasie ruchu, zapobiegając przypadkowemu zjechaniu z trasy.',
    price: 300,
    img: 'images/accessories/wspomaganiePasaRuchu.jpg',
  },
];
