const samochody = [
  {
    id: 0,
    nazwa: 'Kia K5 2025',
    marka: 'Kia',
    model: 'K5',
    img: 'images/cars/kia-k5-2025-02.webp',
    rokProdukcji: 2025,
    kolor: 'srebrny',
    przebiegKm: 15000,
    opis: 'Tutaj będzie opis samochodu',
    cena: 45000,
  },
  {
    id: 1,
    nazwa: 'Toyota Corolla 2020',
    marka: 'Toyota',
    model: 'Corolla',
    img: 'images/cars/Toyota Corolla 2020.avif',
    rokProdukcji: 2020,
    kolor: 'czarny',
    przebiegKm: 20000,
    opis: 'Tutaj będzie opis samochodu',
    cena: 35000,
  },
  {
    id: 2,
    nazwa: 'Ford Mustang GT ',
    marka: 'Ford',
    model: 'Mustang GT',
    img: 'images/cars/Ford Mustang GT.avif',
    rokProdukcji: 2023,
    kolor: 'czerwony',
    przebiegKm: 10000,
    opis: 'Tutaj będzie opis samochodu',
    cena: 60000,
  },
  {
    id: 3,
    nazwa: 'Chevrolet Camaro',
    marka: 'Chevrolet',
    model: 'Camaro ZL1',
    img: 'images/cars/Chevrolet Camaro ZL1.avif',
    rokProdukcji: 2024,
    kolor: 'niebieski',
    przebiegKm: 5000,
    opis: 'Tutaj będzie opis samochodu',
    cena: 70000,
  },
  {
    id: 4,
    nazwa: 'Honda Civic 2022',
    marka: 'Honda',
    model: 'Civic',
    img: 'images/cars/Honda Civic.avif',
    rokProdukcji: 2022,
    kolor: 'biały',
    przebiegKm: 30000,
    opis: 'Tutaj będzie opis samochodu',
    cena: 30000,
  },
  {
    id: 5,
    nazwa: 'BMW 5 Series 2021',
    marka: 'BMW',
    model: '5 Series',
    img: 'images/cars/BMW 5 Series.avif',
    rokProdukcji: 2021,
    kolor: 'szary',
    przebiegKm: 25000,
    opis: 'Tutaj będzie opis samochodu',
    cena: 12000,
  },
  {
    id: 6,
    nazwa: 'Audi A4 2023',
    marka: 'Audi',
    model: 'A4',
    img: 'images/cars/Audi A4.jpg',
    rokProdukcji: 2023,
    kolor: 'zielony',
    przebiegKm: 15000,
    opis: 'Tutaj będzie opis samochodu',
    cena: 51000,
  },
  {
    id: 7,
    nazwa: 'Mercedes-Benz',
    marka: 'Mercedes-Benz',
    model: 'E-Class',
    img: 'images/cars/Mercedez-Benz.avif',
    rokProdukcji: 2022,
    kolor: 'czarny',
    przebiegKm: 20000,
    opis: 'Tutaj będzie opis samochodu',
    cena: 21000,
  },
  {
    id: 8,
    nazwa: 'Volkswagen Golf GTI',
    marka: 'Volkswagen',
    model: 'Golf GTI',
    img: 'images/cars/Volkswagen Golf GTI.avif',
    rokProdukcji: 2023,
    kolor: 'czerwony',
    przebiegKm: 12000,
    opis: 'Tutaj będzie opis samochodu',
    cena: 61000,
  },
  {
    id: 9,
    nazwa: 'Subaru WRX STI 2024',
    marka: 'Subaru',
    model: 'WRX STI',
    img: 'images/cars/Subaru WRX STI.jpg',
    rokProdukcji: 2024,
    kolor: 'niebieski',
    przebiegKm: 8000,
    opis: 'Tutaj będzie opis samochodu',
    cena: 41000,
  },
  {
    nazwa: 'Tesla Model S Plaid 2023',
    marka: 'Tesla',
    model: 'Model S Plaid',
    img: 'images/cars/Tesla Model S Plaid.jpg',
    rokProdukcji: 2023,
    kolor: 'biały',
    przebiegKm: 5000,
    opis: 'Tutaj będzie opis samochodu',
    id: 10,
    cena: 23000,
  },
  {
    nazwa: 'Nissan GT-R Nismo 2024',
    marka: 'Nissan',
    model: 'GT-R Nismo',
    img: 'images/cars/Nissan GT-R Nismo.jpeg',
    rokProdukcji: 2024,
    kolor: 'czarny',
    przebiegKm: 15000,
    opis: 'Tutaj będzie opis samochodu',
    id: 11,
    cena: 15000,
  },
];

const akcesoria = [
  {
    id: 12,
    nazwa: 'Kamera cofania',
    opis: 'Kamera cofania zapewnia dodatkową widoczność podczas cofania, co ułatwia parkowanie i manewrowanie pojazdem.',
    cena: 250,
    img: 'images/accessories/kamera cofania.jpg',
  },
  {
    id: 13,
    nazwa: 'Nawigacja GPS',
    opis: 'System nawigacji GPS pomaga w wyznaczaniu tras i wskazuje optymalne drogi, co ułatwia podróżowanie.',
    cena: 400,
    img: 'images/accessories/nawigacja.jpeg',
  },
  {
    id: 14,
    nazwa: 'System audio premium',
    opis: 'System audio premium oferuje wysoką jakość dźwięku, uprzyjemniając podróżowanie.',
    cena: 600,
    img: 'images/cars/Nissan GT-R Nismo.jpeg',
  },
  {
    id: 15,
    nazwa: 'Tapicerka skórzana',
    opis: 'Tapicerka skórzana dodaje elegancji wnętrzu samochodu oraz zapewnia wygodę podczas podróży.',
    cena: 800,
    img: 'images/cars/Nissan GT-R Nismo.jpeg',
  },
  {
    id: 16,
    nazwa: 'Ogrzewane fotele',
    opis: 'Ogrzewane fotele zapewniają komfort cieplny w chłodne dni, eliminując uczucie zimna podczas jazdy. Przydatne podczas wyjazdu w góry.',
    cena: 350,
    img: 'images/cars/Nissan GT-R Nismo.jpeg',
  },
  {
    id: 17,
    nazwa: 'System monitorowania martwego pola',
    opis: 'System monitorowania martwego pola ostrzega kierowcę o obiektach znajdujących się poza jego polem widzenia.',
    cena: 500,
    img: 'images/cars/Nissan GT-R Nismo.jpeg',
  },
  {
    id: 18,
    nazwa: 'System rozpoznawania znaków drogowych',
    opis: 'Informuje kierowcę o obowiązujących ograniczeniach prędkości i innych znakach drogowych,',
    cena: 450,
    img: 'images/cars/Nissan GT-R Nismo.jpeg',
  },
  {
    id: 19,
    nazwa: 'Dach panoramiczny',
    opis: 'Dach panoramiczny zapewnia widok na niebo i otoczenie, tworząc przestronne i jasne wnętrze samochodu.',
    cena: 1200,
    img: 'images/cars/Nissan GT-R Nismo.jpeg',
  },
  {
    id: 20,
    nazwa: 'System automatycznego parkowania',
    opis: 'System automatycznego parkowania umożliwia precyzyjne parkowanie samochodu, co ułatwia manewrowanie w ciasnych miejscach.',
    cena: 700,
    img: 'images/cars/Nissan GT-R Nismo.jpeg',
  },
  {
    id: 21,
    nazwa: 'Wspomaganie pasa ruchu',
    opis: 'Wspomaganie pasa ruchu pomaga kierowcy utrzymać pojazd na właściwym pasie ruchu, zapobiegając przypadkowemu zjechaniu z trasy.',
    cena: 300,
    img: 'images/cars/Nissan GT-R Nismo.jpeg',
  },
];
